apiVersion: v1
kind: Namespace
metadata:
  name: reactfe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactfe-deployment
  namespace: reactfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactfe
  template:
    metadata:
      labels:
        app: reactfe
    spec:
      containers:
      - name: reactfe
        image: gcr.io/qwiklabs-gcp-03-68357c2ac320/reactfe:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactfe-service
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: reactfe-service.reactfe.svc.cluster.local
  ports:
  - port: 80
#apiVersion: v1
#kind: Service
#metadata:
  #name: reactfe-service
  #namespace: reactfe
#spec:
  #selector:
    #app: reactfe
  #ports:
  #- port: 80
    #targetPort: 80
  #type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reactfe-hpa
  namespace: reactfe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reactfe-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
