apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/qwiklabs-gcp-02-13d47b97d07a/frontend:v1
        ports:
        - containerPort: 8080  # Changed from 80 to 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80            # External port
    targetPort: 8080    # Changed from 80 to 8080 to match container
  type: LoadBalancer
