# product-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image:  gcr.io/qwiklabs-gcp-02-13d47b97d07a/products:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: products
spec:
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 8082
  type: LoadBalancer
